Consistent use of single quotes
hyperledger-labs/solang pull request #770
Opened 2022-04-27 12:11 UTC by seanyoung

We have ‘x’, `x`, and ‘x‘. Always use 'x'.

2022-04-27 12:22 UTC, LucasSte commented
The first commit is already in PR #769 , isn't it?

2022-04-27 12:44 UTC, LucasSte requested changes
All dot files have changed. I've seen some of them, because it would be unfeasible to check them all.

2022-04-27 12:44 UTC, LucasSte commented on src/sema/expression.rs
> +                        "'now' was an alias for 'block.timestamp' in older version of the Solidity language. Please use 'block.timestamp' instead.".to_string(),
This is in another PR. Please remove.

2022-04-27 12:44 UTC, LucasSte commented on tests/contract_testcases/solana/now.dot
> +strict digraph "tests/contract_testcases/solana/now.sol" {
This is in another PR. Please, remove.

2022-04-27 12:44 UTC, LucasSte commented on tests/contract_testcases/solana/now.sol
> +	struct S { int f1; }
This is in another PR. Please, remove.

2022-04-28 13:30 UTC, LucasSte requested changes
Errors messages from the parser still contain double quotes. Can you change that?

2022-04-28 13:32 UTC, seanyoung commented on src/sema/yul/tests/expression.rs
> +        r#"unrecognised token ':=', expected ")", ",", "address", "bool", "break", "byte", "case", "continue", "default", "for", "function", "if", "leave", "let", "return", "revert", "switch", "{", "
Thanks for catching that.

2022-04-28 14:18 UTC, seanyoung commented on src/sema/yul/tests/expression.rs
> +        r#"unrecognised token ':=', expected ")", ",", "address", "bool", "break", "byte", "case", "continue", "default", "for", "function", "if", "leave", "let", "return", "revert", "switch", "{", "
See https://github.com/lalrpop/lalrpop/blob/master/lalrpop/src/lr1/codegen/parse_table.rs#L1538

2022-04-28 16:01 UTC, seanyoung commented on src/sema/yul/tests/expression.rs
> +        r#"unrecognised token ':=', expected ")", ",", "address", "bool", "break", "byte", "case", "continue", "default", "for", "function", "if", "leave", "let", "return", "revert", "switch", "{", "
Hmm it's not quite that simple. The code here https://github.com/lalrpop/lalrpop/blob/master/lalrpop/src/grammar/parse_tree.rs#L907 just using debug for escaping strings.

I think this is a problem for another day.

2022-04-28 17:47 UTC, LucasSte commented on src/sema/yul/tests/expression.rs
> +        r#"unrecognised token ':=', expected ")", ",", "address", "bool", "break", "byte", "case", "continue", "default", "for", "function", "if", "leave", "let", "return", "revert", "switch", "{", "
Ok

2022-04-28 17:51 UTC, LucasSte approved these changes
I haven't checked all dot files in this PR, because there were so many. I selected random one to review, but they all look good. Can you please wait for me to merge #766 before merging this PR? 
There will be many conflicts to solve.

2022-04-28 18:52 UTC, seanyoung commented
> I haven't checked all dot files in this PR, because there were so many. I selected random one to review, but they all look good. Can you please wait for me to merge #766 before merging this PR? There will be many conflicts to solve.

Let me know when that is ready for review. I can deal with the merge conflicts,

2022-04-29 09:51 UTC, merged