Implement assignment to selector and address in Yul
hyperledger-labs/solang pull request #945
Opened 2022-08-01 13:31 UTC by LucasSte

This PR implements assignment to an external function's selector and address in Yul, using the existing infrastructure in Solang.
The logic behind this is going to be used for Borsh decoding and brought up issue #944.

2022-08-01 13:53 UTC, seanyoung requested changes
Would make sense to remove `codegen::Builtin::ExternalFunctionAddress` and `codegen::Builtin::FunctionSelector` to make this consistent? Either that or a comment that they can be removed.

2022-08-01 16:51 UTC, LucasSte commented
> Would make sense to remove `codegen::Builtin::ExternalFunctionAddress` and `codegen::Builtin::FunctionSelector` to make this consistent? Either that or a comment that they can be removed.

Fixed! Thanks for identifying this.

2022-08-02 07:57 UTC, seanyoung approved these changes
Looks great, thanks!

2022-08-02 11:22 UTC, LucasSte commented on src/codegen/mod.rs
> +        if matches!(self.ty(), Type::ExternalFunction { .. }) {
Do we need this assert in debug mode?

2022-08-02 11:27 UTC, seanyoung commented on src/codegen/mod.rs
> +        if matches!(self.ty(), Type::ExternalFunction { .. }) {
Up to you. I'm not a fan of asserts in production code, it can really bloat the code. It does have it uses though.

2022-08-02 12:25 UTC, merged