Organize installation instructions
hyperledger-labs/solang pull request #952
Opened 2022-08-04 16:52 UTC by LucasSte

I reorganized the installation instructions from our docs, making it clear that the one needs to install Solana's LLVM fork before building Solang, following the suggestion from #948.

2022-08-04 18:53 UTC, seanyoung requested changes
This is much clearer, thanks.

This file contains a few lower case "llvm". If you're going to change it to upper case, please make it consistent.

Also do you think its worth mentioning in the top-level `README.md`?

2022-08-04 18:53 UTC, seanyoung commented on docs/installing.rst
> +correct llvm version in your path, simply run:
s/llvm/LLVM

2022-08-04 22:51 UTC, LucasSte commented on docs/installing.rst
> +correct llvm version in your path, simply run:
Fixed

2022-08-04 22:54 UTC, LucasSte commented
I included in the first section a list of our installation methods. The idea behind this is to promptly show the user how they can install Solang.

2022-08-04 22:55 UTC, LucasSte commented
> Also do you think its worth mentioning in the top-level `README.md`?

This is a good idea, but deserves another PR.

2022-08-05 13:17 UTC, seanyoung approved these changes

2022-08-05 16:44 UTC, merged